name: IP地址处理

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 手动触发工作流

env:
  TZ: Asia/Shanghai

jobs:
  process-ip-addresses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download TXT File
      run: |
        wget -O ip_addresses.txt https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset

    - name: Process IP Addresses
      run: |
        # 保留符合IPv4格式的行，并对行进行处理
        grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+(/[0-9]+)?$' ip_addresses.txt > processed_ips.txt
        sed -i 's/^/add list="level1" address="/' processed_ips.txt
        sed -i 's/$/"/' processed_ips.txt
        sed -i '1i /ip firewall address-list' processed_ips.txt
        sed -i '2i remove [find list="level1"]' processed_ips.txt

    - name: Save and Commit Processed File
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add processed_ips.txt
        git commit -m "Processed IP addresses on $(date +'%Y-%m-%d %H:%M:%S')"
        git push
